name: PostgreSQL Materialized View Refresh tool
version: 0.1.4
slug: postgresql_materialized_view_refresh_tool
description: Refresh PostgreSQL materialized views on a regular basis
url: https://github.com/jfurtner/hassio-addons/postgresql-materialized-view-refresh
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  log_level: info
  database_connection_url: postgresql://homeassistant:PASSWORD_GOES_here@77b2833f-timescaledb/homeassistant
  views:
    - name: fan_on_time_since_filter_change
      refresh_frequency_minutes: 5 # time in minutes
      daily_time_24h: "23:59" # 24h time to start from
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  database_connection_url: str
  views:
    - name: str
      refresh_frequency_minutes: int(5,)?
      daily_time_24h: str?
  database_time_zone: str?
tmpfs: true
