name: Subversion Checkin
version: 1.0.5
slug: hass_svn_commit
description: Execute subversion checkin command
url: https://github.com/jfurtner/hass_custom_addin_repository
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: once
boot: manual
options:
  log_level: trace
  svn_username: subversion_user
  svn_password: mySecretPassword
  excludes:
    - .storage
    - zigbee2mqtt/state.json
  mqtt_username: mqtt_user
  mqtt_password: mqtt_password
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  svn_username: str
  svn_password: password
  excludes:
    - str
  mqtt_username: str
  mqtt_password: password
map:
  - config:rw
tmpfs: true