name: Munin-Node

version: 2.0-0.1

slug: munin_node

description: Hosts Munin Node for external use

arch:
  - armhf
  - armv7
  - amd64
  - i386
  - aarch64

startup: application

boot: auto

url: https://github.com/jfurtner/hassio-addons/tree/master/munin-node

init: false

options:
  log_level: debug
  allow:
    - '^192\.0\.2\.1$'
  host_name: "homeassistant.local"

full_access: true

schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  allow:
    - str
  host_name: str

ports:
  "4949/tcp": 4949

ports_description:
  "4949/tcp": Munin node port

tmpfs: true